/* tslint:disable */
/* eslint-disable */
/**
 * Claime Verifier
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from './configuration'
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from './base'

/**
 *
 * @export
 * @interface Claim
 */
export interface Claim {
  /**
   *
   * @type {string}
   * @memberof Claim
   */
  propertyType: string
  /**
   *
   * @type {string}
   * @memberof Claim
   */
  propertyId: string
  /**
   *
   * @type {string}
   * @memberof Claim
   */
  method: string
  /**
   *
   * @type {string}
   * @memberof Claim
   */
  evidence: string
}
/**
 *
 * @export
 * @interface VerifierOutput
 */
export interface VerifierOutput {
  /**
   *
   * @type {string}
   * @memberof VerifierOutput
   */
  result: VerifierOutputResultEnum
  /**
   *
   * @type {string}
   * @memberof VerifierOutput
   */
  error?: string
  /**
   *
   * @type {Claim}
   * @memberof VerifierOutput
   */
  claim: Claim
  /**
   * unix timestamp verified at
   * @type {string}
   * @memberof VerifierOutput
   */
  at: string
  /**
   *
   * @type {VerifierOutputActual}
   * @memberof VerifierOutput
   */
  actual?: VerifierOutputActual
}

/**
 * @export
 * @enum {string}
 */
export enum VerifierOutputResultEnum {
  Verified = 'Verified',
  Failed = 'Failed',
  Unsupported = 'Unsupported',
}

/**
 * hex address got
 * @export
 * @interface VerifierOutputActual
 */
export interface VerifierOutputActual {
  /**
   *
   * @type {string}
   * @memberof VerifierOutputActual
   */
  propertyId: string
  /**
   *
   * @type {string}
   * @memberof VerifierOutputActual
   */
  evidence: string
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} eoa eoa hex address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get: async (eoa: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'eoa' is not null or undefined
      assertParamExists('get', 'eoa', eoa)
      const localVarPath = `/{eoa}`.replace(
        `{${'eoa'}}`,
        encodeURIComponent(String(eoa)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @param {string} eoa eoa hex address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async get(
      eoa: string,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<VerifierOutput>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.get(
        eoa,
        options,
      )
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      )
    },
  }
}

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration)
  return {
    /**
     *
     * @param {string} eoa eoa hex address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(eoa: string, options?: any): AxiosPromise<Array<VerifierOutput>> {
      return localVarFp
        .get(eoa, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @param {string} eoa eoa hex address
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public get(eoa: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .get(eoa, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
