/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RegistryContract } from "./RegistryContract";

export { RegistryContract__factory } from "./factories/RegistryContract__factory";
