/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RegistryContractInterface extends ethers.utils.Interface {
  functions: {
    "allClaimKeys(address,uint256)": FunctionFragment;
    "allClaims(uint256)": FunctionFragment;
    "listClaims(address)": FunctionFragment;
    "register(string,string,string,string)": FunctionFragment;
    "remove(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allClaimKeys",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allClaims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "listClaims", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "allClaimKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allClaims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listClaims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;

  events: {
    "ClaimRemoved(address,tuple)": EventFragment;
    "ClaimUpdated(address,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ClaimRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimUpdated"): EventFragment;
}

export type ClaimRemovedEvent = TypedEvent<
  [
    string,
    [string, string, string, string] & {
      propertyType: string;
      propertyId: string;
      method: string;
      evidence: string;
    }
  ] & {
    claimer: string;
    claim: [string, string, string, string] & {
      propertyType: string;
      propertyId: string;
      method: string;
      evidence: string;
    };
  }
>;

export type ClaimUpdatedEvent = TypedEvent<
  [
    string,
    [string, string, string, string] & {
      propertyType: string;
      propertyId: string;
      method: string;
      evidence: string;
    }
  ] & {
    claimer: string;
    claim: [string, string, string, string] & {
      propertyType: string;
      propertyId: string;
      method: string;
      evidence: string;
    };
  }
>;

export class RegistryContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RegistryContractInterface;

  functions: {
    allClaimKeys(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    allClaims(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        propertyType: string;
        propertyId: string;
        method: string;
        evidence: string;
      }
    >;

    listClaims(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    register(
      propertyType: string,
      propertyId: string,
      method: string,
      evidence: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remove(
      propertyType: string,
      propertyId: string,
      method: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allClaimKeys(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  allClaims(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      propertyType: string;
      propertyId: string;
      method: string;
      evidence: string;
    }
  >;

  listClaims(account: string, overrides?: CallOverrides): Promise<BigNumber[]>;

  register(
    propertyType: string,
    propertyId: string,
    method: string,
    evidence: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remove(
    propertyType: string,
    propertyId: string,
    method: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allClaimKeys(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allClaims(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        propertyType: string;
        propertyId: string;
        method: string;
        evidence: string;
      }
    >;

    listClaims(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    register(
      propertyType: string,
      propertyId: string,
      method: string,
      evidence: string,
      overrides?: CallOverrides
    ): Promise<void>;

    remove(
      propertyType: string,
      propertyId: string,
      method: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ClaimRemoved(address,tuple)"(
      claimer?: null,
      claim?: null
    ): TypedEventFilter<
      [
        string,
        [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        }
      ],
      {
        claimer: string;
        claim: [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        };
      }
    >;

    ClaimRemoved(
      claimer?: null,
      claim?: null
    ): TypedEventFilter<
      [
        string,
        [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        }
      ],
      {
        claimer: string;
        claim: [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        };
      }
    >;

    "ClaimUpdated(address,tuple)"(
      claimer?: null,
      claim?: null
    ): TypedEventFilter<
      [
        string,
        [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        }
      ],
      {
        claimer: string;
        claim: [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        };
      }
    >;

    ClaimUpdated(
      claimer?: null,
      claim?: null
    ): TypedEventFilter<
      [
        string,
        [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        }
      ],
      {
        claimer: string;
        claim: [string, string, string, string] & {
          propertyType: string;
          propertyId: string;
          method: string;
          evidence: string;
        };
      }
    >;
  };

  estimateGas: {
    allClaimKeys(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allClaims(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listClaims(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    register(
      propertyType: string,
      propertyId: string,
      method: string,
      evidence: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remove(
      propertyType: string,
      propertyId: string,
      method: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allClaimKeys(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allClaims(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listClaims(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      propertyType: string,
      propertyId: string,
      method: string,
      evidence: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remove(
      propertyType: string,
      propertyId: string,
      method: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
